InvoiceDemo/Models/Invoice.cs
using System.Linq;

namespace InvoiceDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Invoice")]
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            InvoiceItem = new HashSet<InvoiceItem>();
        }

        public int Id { get; set; }

        [Column(TypeName = "date")]
        public DateTime Invoice_date { get; set; }

        public bool Paid { get; set; }

        private int _dueDate;

        public int Due_date
        {
            get => _dueDate;
            set => _dueDate = value > 0 ? value : 15;
        }

        [NotMapped]
        public decimal TotalPrice
        {
            get
            {
                var sum = InvoiceItem.Where(x => x.Invoice_id == Id).Sum(x => x.Price * x.Quantity);
                return sum;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItem { get; set; }
    }
}

InvoiceDemo/Controllers/InvoiceItemsController.cs
using System;
using System.Net;
using System.Web.Mvc;
using InvoiceDemo.Models;
using InvoiceDemo.Models.Viewmodels;
using InvoiceDemo.Repositories;

namespace InvoiceDemo.Controllers
{
    public class InvoiceItemsController : Controller
    {
        private readonly IInvoiceItemRepository _repository;

        public InvoiceItemsController(IInvoiceItemRepository repository)
        {
            _repository = repository;
        }

        // GET: InvoiceItems/Create
        public ActionResult Create(int? invoice)
        {
            if (invoice == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View();
        }

        // POST: InvoiceItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateInvoiceItemVm invoiceItem, int? invoice)
        {
            if (ModelState.IsValid)
            {
                InvoiceItem item = new InvoiceItem()
                {
                    Name = invoiceItem.Name,
                    Price = invoiceItem.Price,
                    Quantity = invoiceItem.Quantity
                };

                try
                {
                    _repository.CreateInvoiceItem(item, invoice);
                    return RedirectToAction("Details", "Invoices", new {id = invoice});
                }
                catch (ArgumentException e)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }

            return View(invoiceItem);
        }

        // GET: InvoiceItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var invoiceItem = _repository.GetInvoiceItem(id);

            if (invoiceItem == null)
            {
                return HttpNotFound();
            }

            DeleteInvoiceItemVm invoiceItemVm = new DeleteInvoiceItemVm()
            {
                Name = invoiceItem.Name,
                Price = invoiceItem.Price,
                Quantity = invoiceItem.Quantity
            };

            return View(invoiceItemVm);
        }

        // POST: InvoiceItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _repository.DeleteInvoiceItem(id);
            return RedirectToAction("Index", "Invoices");
        }

        protected override void Dispose(bool disposing)
        {
            _repository.Dispose();
            base.Dispose(disposing);
        }
    }
}

InvoiceDemo/Controllers/InvoicesController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Mvc;
using InvoiceDemo.Models;
using InvoiceDemo.Models.Viewmodels;
using InvoiceDemo.Models.Viewmodels.API;
using InvoiceDemo.Repositories;
using JsonPatch;
using EditInvoiceVm = InvoiceDemo.Models.Viewmodels.EditInvoiceVm;

namespace InvoiceDemo.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly IInvoiceRepository _repository;

        public InvoicesController(IInvoiceRepository repository)
        {
            _repository = repository;
        }

        // GET: Invoices
        public ActionResult Index()
        {
            var invoices = from e in _repository.GetInvoices()
                           select new InvoiceDetailVm
                           {
                               Id = e.Id,
                               InvoiceDate = e.Invoice_date,
                               DueDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, e.Due_date),
                               Paid = e.Paid.ToString(),
                               TotalPrice = e.TotalPrice
                           };

            return View(invoices.ToList());
        }

        // GET: Invoices/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var invoice = _repository.GetInvoice(id);

            if (invoice == null)
            {
                return HttpNotFound();
            }

            InvoiceDetailVm detailVm = new InvoiceDetailVm()
            {
                Id = invoice.Id,
                InvoiceDate = invoice.Invoice_date,
                DueDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, invoice.Due_date),
                Paid = invoice.Paid.ToString(),
                TotalPrice = invoice.TotalPrice,
                InvoiceItem = invoice.InvoiceItem
            };

            return View(detailVm);
        }

        // GET: Invoices/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateInvoiceVm invoiceVm)
        {
            if (ModelState.IsValid)
            {
                Invoice invoice = new Invoice()
                {
                    Invoice_date = invoiceVm.InvoiceDate,
                    Paid = invoiceVm.Paid,
                    Due_date = invoiceVm.DueDate
                };

                _repository.CreateInvoice(invoice);
                return RedirectToAction("Details", new { id = invoice.Id });
            }

            return View(invoiceVm);
        }

        // GET: Invoices/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var invoice = _repository.GetInvoice(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }

            EditInvoiceVm vm = new EditInvoiceVm
            {
                Id = invoice.Id,
                InvoiceDate = invoice.Invoice_date,
                DueDate = invoice.Due_date,
                Paid = invoice.Paid,
                InvoiceItem = from e in invoice.InvoiceItem
                              select new InvoiceItemVm
                              {
                                  Id = e.Id,
                                  Name = e.Name,
                                  Price = e.Price,
                                  Quantity = e.Quantity
                              }
            };
            return View(vm);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditInvoiceVm invoiceVm)
        {
            if (ModelState.IsValid)
            {
                Invoice invoice = new Invoice()
                {
                    Id = invoiceVm.Id,
                    Invoice_date = invoiceVm.InvoiceDate,
                    Due_date = invoiceVm.DueDate,
                    Paid = invoiceVm.Paid
                };

                _repository.EditInvoice(invoice);
                return RedirectToAction("Index");
            }
            return View(invoiceVm);
        }

        protected override void Dispose(bool disposing)
        {
            _repository.Dispose();
            base.Dispose(disposing);
        }
    }
}

namespace InvoiceDemo.Controllers.Api
{
    public class InvoicesController : ApiController
    {
        private readonly InvoiceRepository _repository = new InvoiceRepository();

        public IHttpActionResult GetUnpaidInvoices()
        {
            var result = from e in _repository.GetUnpaidInvoices()
                         select new UnpaidInvoiceVm
                         {
                             InvoiceDate = e.Invoice_date,
                             DueDate = e.Due_date,
                             Paid = e.Paid.ToString(),
                             TotalPrice = e.TotalPrice
                         };

            return Ok(result);
        }

        // PUT: api/invoices
        public IHttpActionResult Put([FromBody] PayVm payViewmodel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Invoice invoice = new Invoice()
            {
                Id = payViewmodel.Id,
                Paid = payViewmodel.Paid
            };

            try
            {
                _repository.EditInvoice(invoice);
                return Ok();

            }
            catch (ArgumentException e)
            {
                return BadRequest(e.Message);
            }
        }

        [System.Web.Http.HttpPatch]
        public IHttpActionResult EditInvoice(int id, [FromBody]JsonPatchDocument<Models.Viewmodels.API.EditInvoiceVm> patchData)
        {
            var invoice = _repository.GetInvoice(id);
            if (invoice == null)
            {
                return BadRequest("Invoice does not exist.");
            }

            if (patchData == null)
            {
                return BadRequest("Request body is empty");
            }

            Models.Viewmodels.API.EditInvoiceVm vm = new Models.Viewmodels.API.EditInvoiceVm
            {
                InvoiceDate = invoice.Invoice_date,
                DueDate = invoice.Due_date,
                Paid = invoice.Paid
            };

            patchData.ApplyUpdatesTo(vm);

            Invoice inv = new Invoice()
            {
                Id = id,
                Invoice_date = vm.InvoiceDate,
                Due_date = vm.DueDate,
                Paid = vm.Paid
            };

            _repository.EditInvoice(inv);
            return Ok();
        }
    }
}

InvoiceDemo/Views/Invoices/Create.cshtml
@model InvoiceDemo.Models.Viewmodels.CreateInvoiceVm

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paid)
                    @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InvoiceDemo/Views/Invoices/DetailListItems.cshtml
@model IEnumerable<InvoiceDemo.Models.InvoiceItem>

<h3>Položky</h3>
@{
    if (Model.Any())
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>Faktura nemá žádné položky.</p>
    }
}

InvoiceDemo/Views/Invoices/Details.cshtml
@model InvoiceDemo.Models.Viewmodels.InvoiceDetailVm

@{
    ViewBag.Title = "Details";
}

<style>
    .invoice-detail {
        margin: 20px 0 30px 0;
    }

    .property {
        margin: 5px 0;
    }

    .display-name {
        display: inline-block;
        font-weight: 600;
        min-width: 130px;
    }

    .display-value {
        display: inline-block
    }
</style>

<h2>Detail</h2>

<div class="invoice-detail">
    <div class="property">
        <div class="display-name">@Html.DisplayNameFor(model => model.InvoiceDate)</div>
        <div class="display-value">@Html.DisplayFor(model => model.InvoiceDate)</div>
    </div>
    
    <div class="property">
        <div class="display-name">@Html.DisplayNameFor(model => model.DueDate)</div>
        <div class="display-value">@Html.DisplayFor(model => model.DueDate)</div>
    </div>

    <div class="property">
        <div class="display-name">@Html.DisplayNameFor(model => model.Paid)</div>
        <div class="display-value">@Html.DisplayFor(model => model.Paid)</div>
    </div>
</div>

@Html.Partial("DetailListItems", Model.InvoiceItem)

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

InvoiceDemo/Views/Invoices/Edit.cshtml
@model InvoiceDemo.Models.Viewmodels.EditInvoiceVm

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.InvoiceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InvoiceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InvoiceDate, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Paid)
                    @Html.ValidationMessageFor(model => model.Paid, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
@Html.ActionLink("Add Item", "Create", "InvoiceItems", new {invoice = Model.Id}, null)
@Html.Partial("EditListItems", Model.InvoiceItem)

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InvoiceDemo/Views/Invoices/EditListItems.cshtml
@model IEnumerable<InvoiceDemo.Models.Viewmodels.InvoiceItemVm>

<h3>Položky</h3>
@{
    if (Model.Any())
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", "InvoiceItems", new { id= item.Id}, null) 
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>Faktura nemá žádné položky.</p>
    }
}

InvoiceDemo/Views/Invoices/Index.cshtml
@model List<InvoiceDemo.Models.Viewmodels.InvoiceDetailVm>

@{
    ViewBag.Title = "Index";
}

<h2>My Invoices</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model[0].InvoiceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model[0].Paid)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.InvoiceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paid)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
}

</table>